name = "Scrumblers Serverpack"
author = "Tlp"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "52577d8c680a020f974ae8d18f63d109275ebc79b4e19283d62a06bb6f4255f6"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
