name = "Scrumblers Serverpack"
author = "Tlp"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ace03f1f64a639e4b2362fa4be62f9749fe1e720e809f1faf05496e6b9507aba"

[versions]
minecraft = "1.20.1"
neoforge = "1.20.1-47.1.106"
