name = "Scrumblers Serverpack"
author = "Tlp"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e7b2a21d9d3849f1044229d06812ec684e3826c10263c8c7344d55365b002a1b"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
