name = "Scrumblers Serverpack"
author = "Tlp"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6f54ec208d57661e304511d16784e49089c7d636585ba3c67bdd3229d7e064a5"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
