name = "Scrumblers Serverpack"
author = "Tlp"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7557c7c1680330cde10c80fdaf8f9e34c9cc1ad031c95fe893db6bc8e55bf921"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
