name = "Scrumblers Serverpack"
author = "Tlp"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1aa7f2b4769a70399bef31ffab052e42581811613af123d13de4eed7a429970b"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
