
#Disables certain types. Note that all these configs, like in any other mod, only hide stuff from tabs and disable their recipes
[types]

	[types.cut_block_type]

		[types.cut_block_type.mowziesmobs]
			painted_acacia = true

		[types.cut_block_type.environmental]
			dirt_brick = true
			dirt_tile = true
			smooth_mud = true
			grass_thatch = true
			cattail_thatch = true
			duckweed_thatch = true
			willow = true
			pine = true
			plum = true
			wisteria = true

		[types.cut_block_type.savage_and_ravage]
			gloomy_tile = true

		[types.cut_block_type.clayworks]
			terracotta = true
			white_terracotta = true
			orange_terracotta = true
			magenta_terracotta = true
			light_blue_terracotta = true
			yellow_terracotta = true
			lime_terracotta = true
			pink_terracotta = true
			gray_terracotta = true
			light_gray_terracotta = true
			cyan_terracotta = true
			purple_terracotta = true
			blue_terracotta = true
			brown_terracotta = true
			green_terracotta = true
			red_terracotta = true
			black_terracotta = true
			terracotta_brick = true
			white_terracotta_brick = true
			orange_terracotta_brick = true
			magenta_terracotta_brick = true
			light_blue_terracotta_brick = true
			yellow_terracotta_brick = true
			lime_terracotta_brick = true
			pink_terracotta_brick = true
			gray_terracotta_brick = true
			light_gray_terracotta_brick = true
			cyan_terracotta_brick = true
			purple_terracotta_brick = true
			blue_terracotta_brick = true
			brown_terracotta_brick = true
			green_terracotta_brick = true
			red_terracotta_brick = true
			black_terracotta_brick = true

		[types.cut_block_type.hexcasting]
			edified = true

		[types.cut_block_type.caverns_and_chasms]
			sanguine_tile = true
			fortified_sanguine_tile = true
			spinel_brick = true
			lapis_brick = true
			cobblestone_brick = true
			mossy_cobblestone_brick = true
			cobblestone_tile = true
			mossy_cobblestone_tile = true
			cobbled_deepslate_brick = true
			cobbled_deepslate_tile = true
			calcite = true
			polished_calcite = true
			tuff = true
			polished_tuff = true
			sugilite = true
			polished_sugilite = true
			dripstone_shingle = true
			cut_amethyst_brick = true
			azalea = true

		[types.cut_block_type.upgrade_aquatic]
			beachgrass_thatch = true
			luminous_prismarine = true
			tooth_brick = true
			scute_shingle = true
			scute_pavement = true
			coralstone = true
			bubble_coralstone = true
			horn_coralstone = true
			tube_coralstone = true
			brain_coralstone = true
			fire_coralstone = true
			acan_coralstone = true
			finger_coralstone = true
			star_coralstone = true
			moss_coralstone = true
			petal_coralstone = true
			branch_coralstone = true
			rock_coralstone = true
			pillow_coralstone = true
			silk_coralstone = true
			chrome_coralstone = true
			prismarine_coralstone = true
			elder_prismarine_coralstone = true
			dead_coralstone = true
			kelpy_cobblestone = true
			kelpy_stone_brick = true
			kelpy_cobblestone_brick = true
			kelpy_cobblestone_tile = true
			driftwood = true
			river = true

		[types.cut_block_type.endergetic]
			poise = true
			eumus_brick = true

		[types.cut_block_type.neapolitan]
			chocolate_brick = true
			chocolate_tile = true
			frond_thatch = true

		[types.cut_block_type.alexscaves]
			galena = true
			galena_brick = true
			limestone = true
			smooth_limestone = true
			pewen = true
			radrock = true
			radrock_brick = true
			cinder_block = true
			abyssmarine = true
			abyssmarine_brick = true
			smooth_bone = true
			guanostone = true
			guanostone_brick = true
			coprolith = true
			smooth_coprolith = true
			thornwood = true
			gingerbread_brick = true
			frosted_gingerbread_brick = true

		[types.cut_block_type.atmospheric]
			rosewood = true
			morado = true
			ivory_travertine = true
			peach_travertine = true
			persimmon_travertine = true
			saffron_travertine = true
			dolerite = true
			polished_dolerite = true
			arid_sandstone = true
			smooth_arid_sandstone = true
			cut_arid_sandstone = true
			red_arid_sandstone = true
			smooth_red_arid_sandstone = true
			cut_red_arid_sandstone = true
			yucca = true
			aspen = true
			laurel = true
			kousa = true
			grimwood = true
			carmine_shingle = true
			carmine_pavement = true

		[types.cut_block_type.create]
			copper_shingle = true
			exposed_copper_shingle = true
			weathered_copper_shingle = true
			oxidized_copper_shingle = true
			waxed_copper_shingle = true
			waxed_exposed_copper_shingle = true
			waxed_weathered_copper_shingle = true
			waxed_oxidized_copper_shingle = true
			copper_tile = true
			exposed_copper_tile = true
			weathered_copper_tile = true
			oxidized_copper_tile = true
			waxed_copper_tile = true
			waxed_exposed_copper_tile = true
			waxed_weathered_copper_tile = true
			waxed_oxidized_copper_tile = true
			cut_granite = true
			polished_cut_granite = true
			cut_granite_brick = true
			small_granite_brick = true
			cut_diorite = true
			polished_cut_diorite = true
			cut_diorite_brick = true
			small_diorite_brick = true
			cut_andesite = true
			polished_cut_andesite = true
			cut_andesite_brick = true
			small_andesite_brick = true
			cut_calcite = true
			polished_cut_calcite = true
			cut_calcite_brick = true
			small_calcite_brick = true
			cut_dripstone = true
			polished_cut_dripstone = true
			cut_dripstone_brick = true
			small_dripstone_brick = true
			cut_deepslate = true
			polished_cut_deepslate = true
			cut_deepslate_brick = true
			small_deepslate_brick = true
			cut_tuff = true
			polished_cut_tuff = true
			cut_tuff_brick = true
			small_tuff_brick = true
			cut_asurine = true
			polished_cut_asurine = true
			cut_asurine_brick = true
			small_asurine_brick = true
			cut_crimsite = true
			polished_cut_crimsite = true
			cut_crimsite_brick = true
			small_crimsite_brick = true
			cut_limestone = true
			polished_cut_limestone = true
			cut_limestone_brick = true
			small_limestone_brick = true
			cut_ochrum = true
			polished_cut_ochrum = true
			cut_ochrum_brick = true
			small_ochrum_brick = true
			cut_scoria = true
			polished_cut_scoria = true
			cut_scoria_brick = true
			small_scoria_brick = true
			cut_scorchia = true
			polished_cut_scorchia = true
			cut_scorchia_brick = true
			small_scorchia_brick = true
			cut_veridium = true
			polished_cut_veridium = true
			cut_veridium_brick = true
			small_veridium_brick = true

		[types.cut_block_type.quark]
			ancient_planks = true
			azalea_planks = true
			blossom_planks = true
			duskbound_block = true
			iron_plate = true
			rusty_iron_plate = true
			midori_block = true
			blue_nether_bricks = true
			sandstone_bricks = true
			red_sandstone_bricks = true
			soul_sandstone_bricks = true
			cobblestone_bricks = true
			mossy_cobblestone_bricks = true
			blackstone_bricks = true
			dirt_bricks = true
			netherrack_bricks = true
			limestone = true
			polished_limestone = true
			jasper = true
			polished_jasper = true
			shale = true
			polished_shale = true
			myalite = true
			polished_myalite = true
			permafrost = true
			permafrost_bricks = true
			raw_iron_bricks = true
			raw_gold_bricks = true
			raw_copper_bricks = true
			shingles = true
			white_shingles = true
			orange_shingles = true
			magenta_shingles = true
			light_blue_shingles = true
			yellow_shingles = true
			lime_shingles = true
			pink_shingles = true
			gray_shingles = true
			light_gray_shingles = true
			cyan_shingles = true
			purple_shingles = true
			blue_shingles = true
			brown_shingles = true
			green_shingles = true
			red_shingles = true
			black_shingles = true
			soul_sandstone = true
			cut_soul_sandstone = true
			smooth_soul_sandstone = true
			thatch = true
			calcite = true
			polished_calcite = true
			dripstone_block = true
			polished_dripstone = true
			tuff = true
			polished_tuff = true
			granite_bricks = true
			diorite_bricks = true
			andesite_bricks = true
			calcite_bricks = true
			dripstone_bricks = true
			tuff_bricks = true
			limestone_bricks = true
			jasper_bricks = true
			shale_bricks = true
			myalite_bricks = true

		[types.cut_block_type.mynethersdelight]
			powdery = true
			powdery_mosaic = true

		[types.cut_block_type.supplementaries]
			fine_wood = true
			lapis_bricks = true
			ash_bricks = true
			stone_tile = true
			blackstone_tile = true

		[types.cut_block_type.spectrum]
			smooth_basalt = true
			planed_basalt = true
			polished_basalt = true
			basalt_brick = true
			basalt_tile = true
			calcite = true
			planed_calcite = true
			polished_calcite = true
			calcite_brick = true
			calcite_tile = true
			blackslag = true
			cobbled_blackslag = true
			polished_blackslag = true
			blackslag_tile = true
			blackslag_brick = true
			polished_shale_clay = true
			exposed_polished_shale_clay = true
			weathered_polished_shale_clay = true
			shale_clay_brick = true
			exposed_shale_clay_brick = true
			weathered_shale_clay_brick = true
			shale_clay_tile = true
			exposed_shale_clay_tile = true
			weathered_shale_clay_tile = true
			polished_bone_ash = true
			bone_ash_brick = true
			bone_ash_tile = true
			basal_marble = true
			polished_basal_marble = true
			basal_marble_tile = true
			basal_marble_brick = true
			pyrite = true
			pyrite_tiles = true
			white = true
			orange = true
			magenta = true
			light_blue = true
			yellow = true
			lime = true
			pink = true
			gray = true
			light_gray = true
			cyan = true
			purple = true
			blue = true
			brown = true
			green = true
			red = true
			black = true
			slate_noxwood = true
			ebony_noxwood = true
			ivory_noxwood = true
			chestnut_noxwood = true
			weeping_gala = true

		[types.cut_block_type.malum]
			tainted_rock = true
			smooth_tainted_rock = true
			polished_tainted_rock = true
			tainted_rock_bricks = true
			tainted_rock_tiles = true
			small_tainted_rock_bricks = true
			runic_tainted_rock_bricks = true
			runic_tainted_rock_tiles = true
			runic_small_tainted_rock_bricks = true
			twisted_rock = true
			smooth_twisted_rock = true
			polished_twisted_rock = true
			twisted_rock_bricks = true
			twisted_rock_tiles = true
			small_twisted_rock_bricks = true
			runic_twisted_rock_bricks = true
			runic_twisted_rock_tiles = true
			runic_small_twisted_rock_bricks = true
			runewood_boards = true
			vertical_runewood_boards = true
			runewood_planks = true
			rustic_runewood_planks = true
			vertical_runewood_planks = true
			vertical_rustic_runewood_planks = true
			runewood_tiles = true
			rustic_runewood_tiles = true
			soulwood_boards = true
			vertical_soulwood_boards = true
			soulwood_planks = true
			rustic_soulwood_planks = true
			vertical_soulwood_planks = true
			vertical_rustic_soulwood_planks = true
			soulwood_tiles = true
			rustic_soulwood_tiles = true

		[types.cut_block_type.biomesoplenty]
			white_sandstone = true
			smooth_white_sandstone = true
			cut_white_sandstone = true
			orange_sandstone = true
			smooth_orange_sandstone = true
			cut_orange_sandstone = true
			black_sandstone = true
			smooth_black_sandstone = true
			cut_black_sandstone = true
			brimstone_brick = true
			fir = true
			redwood = true
			mahogany = true
			jacaranda = true
			palm = true
			willow = true
			dead = true
			magic = true
			umbran = true
			hellbark = true
			pine = true
			maple = true
			empyreal = true

		[types.cut_block_type.naturalist]
			shellstone = true
			shellstone_brick = true
			cut_shellstone = true
			smooth_shellstone = true

		[types.cut_block_type.autumnity]
			snail_shell_brick = true
			snail_shell_tile = true
			maple = true

		[types.cut_block_type.buzzier_bees]
			honeycomb_brick = true
			honeycomb_tile = true

		[types.cut_block_type.gardens_of_the_dead]
			soulblight = true
			whistlecane = true
			whistlecane_mosaic = true

		[types.cut_block_type.tetra]
			forged_platform = true

		[types.cut_block_type.mna]
			pilgrims_path = true
			"decoration/arcane_stone" = true
			"decoration/vinteum_arcane_stone" = true
			"decoration/redstone_arcane_stone" = true
			"decoration/chimerite_arcane_stone" = true
			"decoration/amethyst_arcane_stone" = true
			"decoration/gold_arcane_stone" = true
			"decoration/quicksilver_arcane_stone" = true
			"decoration/copper_arcane_stone" = true
			"decoration/diamond_arcane_stone" = true
			"decoration/emerald_arcane_stone" = true
			"decoration/arcane_sandstone" = true
			"decoration/vinteum_arcane_sandstone" = true
			"decoration/redstone_arcane_sandstone" = true
			"decoration/chimerite_arcane_sandstone" = true
			"decoration/emerald_arcane_sandstone" = true
			"decoration/amethyst_arcane_sandstone" = true
			"decoration/gold_arcane_sandstone" = true
			"decoration/quicksilver_arcane_sandstone" = true
			"decoration/copper_arcane_sandstone" = true
			"decoration/diamond_arcane_sandstone" = true

	[types.wood_type]

		[types.wood_type.environmental]
			willow = true
			pine = true
			plum = true
			wisteria = true

		[types.wood_type.hexcasting]
			edified = true

		[types.wood_type.caverns_and_chasms]
			azalea = true

		[types.wood_type.mynethersdelight]
			powdery = true

		[types.wood_type.quark]
			azalea = true
			ancient = true
			blossom = true

		[types.wood_type.upgrade_aquatic]
			driftwood = true
			river = true

		[types.wood_type.endergetic]
			poise = true

		[types.wood_type.alexscaves]
			pewen = true
			thornwood = true

		[types.wood_type.atmospheric]
			rosewood = true
			morado = true
			yucca = true
			aspen = true
			laurel = true
			kousa = true
			grimwood = true

		[types.wood_type.spectrum]
			ivory_noxwood = true
			slate_noxwood = true
			ebony_noxwood = true
			chestnut_noxwood = true
			white = true
			orange = true
			magenta = true
			light_blue = true
			yellow = true
			lime = true
			pink = true
			gray = true
			light_gray = true
			cyan = true
			purple = true
			blue = true
			brown = true
			green = true
			red = true
			black = true
			weeping_gala = true

		[types.wood_type.malum]
			runewood = true
			soulwood = true

		[types.wood_type.biomesoplenty]
			fir = true
			redwood = true
			mahogany = true
			jacaranda = true
			palm = true
			willow = true
			dead = true
			magic = true
			umbran = true
			hellbark = true
			pine = true
			maple = true
			empyreal = true

		[types.wood_type.gardens_of_the_dead]
			soulblight = true
			whistlecane = true

		[types.wood_type.autumnity]
			maple = true

	[types.leaves_type]

		[types.leaves_type.environmental]
			pink_wisteria = true
			blue_wisteria = true
			purple_wisteria = true
			white_wisteria = true
			cheerful_plum = true
			moody_plum = true
			hibiscus = true
			willow = true
			pine = true
			plum = true
			wisteria = true

		[types.leaves_type.hexcasting]
			amethyst_edified = true
			aventurine_edified = true
			citrine_edified = true

		[types.leaves_type.alexscaves]
			ancient = true

		[types.leaves_type.upgrade_aquatic]
			river = true

		[types.leaves_type.atmospheric]
			rosewood = true
			morado = true
			flowering_morado = true
			yucca = true
			aspen = true
			green_aspen = true
			laurel = true
			dry_laurel = true
			kousa = true
			currant = true
			grimwood = true

		[types.leaves_type.quark]
			ancient = true
			blue_blossom = true
			lavender_blossom = true
			orange_blossom = true
			yellow_blossom = true
			red_blossom = true

		[types.leaves_type.spectrum]
			white = true
			orange = true
			magenta = true
			light_blue = true
			yellow = true
			lime = true
			pink = true
			gray = true
			light_gray = true
			cyan = true
			purple = true
			blue = true
			brown = true
			green = true
			red = true
			black = true
			weeping_gala = true
			nephrite_blossom = true
			spirit_sallow = true

		[types.leaves_type.malum]
			runewood = true
			azure_runewood = true
			soulwood = true
			budding_soulwood = true

		[types.leaves_type.biomesoplenty]
			origin = true
			flowering_oak = true
			rainbow_birch = true
			snowblossom = true
			fir = true
			redwood = true
			mahogany = true
			jacaranda = true
			palm = true
			willow = true
			dead = true
			magic = true
			umbran = true
			hellbark = true
			red_maple = true
			orange_maple = true
			yellow_maple = true
			null = true
			cypress = true
			pine = true
			empyreal = true

		[types.leaves_type.autumnity]
			yellow_maple = true
			orange_maple = true
			red_maple = true
			maple = true

	[types.cake]

		[types.cake.neapolitan]
			vanilla_cake = true
			chocolate_cake = true
			strawberry_cake = true
			banana_cake = true
			mint_cake = true
			adzuki_cake = true

		[types.cake.farmersrespite]
			coffee_cake = true

		[types.cake.mynethersdelight]
			magma_cake = true

#Disables specific entries
[entries]

	[entries.wood_type]

		[entries.wood_type.handcrafted]
			counter = true
			corner_trim = true
			fancy_bed = true
			desk = true
			shelf = true
			nightstand = true
			cupboard = true
			dining_bench = true
			bench = true
			couch = true
			table = true
			chair = true
			drawer = true
			pillar_trim = true
			side_table = true

		[entries.wood_type.boatload]
			large_boat = true
			furnace_boat = true

		[entries.wood_type.create]
			window = true
			window_pane = true

		[entries.wood_type.farmersdelight]
			cabinet = true

		[entries.wood_type.quark]
			hollow_log = true
			vertical_planks = true
			post = true
			trapped_chest = true
			bookshelf = true
			chest = true
			stripped_post = true
			ladder = true
			vertical_slab = true

		[entries.wood_type.backpacked]
			backpack_shelf = true

	[entries.leaves_type]

		[entries.leaves_type.quark]
			hedge = true
			leaf_carpet = true

