name = "Blawg & Artifice"
author = "Tlp"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1ac78190fe31e941fd3828381bb807f6a385bc8262be11fc736fe0bc4e016a16"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
