name = "Scrim3ers"
author = "Tlp"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "87144e3c6b02fff06f7655a52a21577e626dd1ef0e9bc70660e8ffe9d6ec8f5f"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
