name = "Scrim3ers"
author = "Tlp"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8bdb09dee9d1f85f8e27218bea7a75d03e0ba6140461e7ca58ec1bdd7bd27eda"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
