name = "Scrim3ers"
author = "Tlp"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "15ef3ac699c55c98b002fc5b8e5790a899ae05d6ac6180c40f181c17d9cdbc1d"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
