name = "Scrim3ers"
author = "Tlp"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "35118102620526c0995ab7d7805829fcdd86881070dde922f587bdbae472dcd6"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
