name = "Scrim3ers"
author = "Tlp"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bae705c9a2e6527e38f241f2a5ddf57a4c9a24b16fcc2dc3c509802d6d443fa3"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
