name = "Scrim3ers"
author = "Tlp"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d4af9be7789c51e4e934380f7e747ccc919488bb667c9a99ef0000662748f8c0"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
