name = "Scrim3ers"
author = "Tlp"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0f18ea7d38470f4f13acb00c8b1445726aa972f1a0e491e8a3346cb302b8c0eb"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
