name = "Scrim3ers"
author = "Tlp"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "26edaa87a43791830d507ca5338ebeef4008aa51819f9307abfeb6f0f54c3347"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
