name = "Scrim3ers"
author = "Tlp"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8387e873259501f0c28f24b0920bb567d7913e6d156ff6b21b31f1c7f7409153"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
