name = "Scrim3ers"
author = "Tlp"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b565354ca3c394811c3d187417f01cf583600300742147b322f9f6bd07cac7a7"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
