name = "Scrim3ers"
author = "Tlp"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "096d81517307c4cc5ddf7536b158a8695de6d70d3edfb97afc8df57e1f14ee62"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
