name = "Scrim3ers"
author = "Tlp"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a8c0c2d45bd73e37a69848d179909569109f53b86071f750e88a60e2b1c7e751"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
