name = "Scrim3ers"
author = "Tlp"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7b155aba8f23d4d1a3196ac0a31aa45f1e2f8c657024d7a5a379df1912d79282"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
