name = "Scrim3ers"
author = "Tlp"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "83104d8794c30096d8280d61bb38d452a8f2a0dc62d61346cd49b532fd19cda2"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
