name = "Scrim3ers"
author = "Tlp"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a9729aeae9a5bbce94327e1a14151b9685ce7e8bfc5351c5172022660c91e0ab"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
