name = "Scrim3ers"
author = "Tlp"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5fc277ce6f5d1f254f40b0611c6d8152a61090ad05dc656cac69cf126f3a4eea"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
