name = "Scrim3ers"
author = "Tlp"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e29cfadbe42bb7156ca02190f89835ce8e3d9aa3d61451464390aba31982c6ed"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
