name = "Scrim3ers"
author = "Tlp"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2fd3f7c2565ee7a10458ac42160770eaae9c7c0e5a8a460d6c825f3df4b6d119"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
