name = "Scrim3ers"
author = "Tlp"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9b34c23e83371c6082323a230f40b3a3b8b0366f0b64b8c98fcdbff27c3d3c07"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
