name = "Scrumblers"
author = "Tlp"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "72ce75101dc83f3d387e5f86b80e50895d03f35e1092032daf9472928f64f64e"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
