name = "Scrumblers"
author = "Tlp"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4500efc3ddb5d93b70b3ddf620956003bd18685f8e0147a1b9958cb097394c58"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
