name = "Scrumblers"
author = "Tlp"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "95f8a429b38aff46672eebb9dd3b49ae79f83ba43509c07875be40e786311e83"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
