name = "Scrumblers"
author = "Tlp"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "174ca4388c1223fa2ea0e2d1f7b32f8a7af56a3ef4324e54adf1f1b7467d35fa"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
