name = "Scrumblers"
author = "Tlp"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "13e0f71d1b151e2240f0d2ec9d35a49be9ad3a1066701bf6032073606c209bc4"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
